
on: [push]

jobs:
    deploy-test:
        runs-on: ubuntu-latest
        name: Library deploy test job
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - uses: ./.github/actions/deploy.yml
